### ISSUE TITLE
About Permissions

### ISSUE THREAD

**Issue by berkayyibis** [banbar/GMT-456-GIS-Programming#9]
@banbar  Since we do not have permission to upload files, we cannot add the required 'group-1-readme.md' and image files. We had to try the merge process because we did not have permission. We will be happy if you can open our permissions.

**Comment by banbar** [comment]
@berkayyibis First you need to **Fork** the course's GitHub page, and then you can **create a Pull Request**. So, you don't really need a permission.

It seems that you sorted it. :)

**Comment by berkayyibis** [comment]
@banbar We couldn't think you were doing it on purpose. We have already sent a pull request for trial purposes. Of course, we can do it using the method you say. Thank for your explanation :) .
